spring:
  application:
    name: ew-sso-api
  main:
#    banner-mode: false
    log-startup-info: false
    allow-bean-definition-overriding: true
  profiles:
    include: microservice
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    mapper:
      default-view-inclusion: true     
#springfox:
#  documentation:
#    auto-startup: true
#    swagger:
#      v2:
#        home: /api/v2/docs
#        host: ew-sso-dev.westeurope.cloudapp.azure.com
server:  
  undertow:
    worker-threads: 500
  port: ${PORT:2205}
  servlet:
    contextPath: /ew-sso-api
keycloak:
  auth-server-url: http://ew-sso-dev.westeurope.cloudapp.azure.com/auth
  realm: eurowag
  username: wagadmin
  password: xara2002
  client-id: admin-cli
#keycloak:
#  auth-server-url: http://sso.karumien.com/auth
#  resource: admin-cli
#  realm: eurowag
#  public-client: true
#  principal-attribute: karadmin
security:
  ignored: /swagger-resources/**
 