spring:
  application:
    name: ew-sso-api
  main:
    log-startup-info: false
    allow-bean-definition-overriding: true
  profiles:
    include: microservice
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    mapper:
      default-view-inclusion: true     
server:  
  undertow:
    worker-threads: 500
  port: ${PORT:2205}
  servlet:
    contextPath: ${CONTEXT_PATH:/api/v1/sso}
keycloak:
  auth-server-url: http://ew-sso-dev.westeurope.cloudapp.azure.com/auth
  realm: eurowag
  username: wagadmin
  password: xara2002
  client-id: admin-cli
 