spring:
#  devtools.restart.enabled=false
  application:
    name: ew-sso-api
    env: ${ENVIRONMENT:dev}
  main:
    log-startup-info: false
    allow-bean-definition-overriding: true
  profiles:
    include: microservice
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    mapper:
      default-view-inclusion: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_ADDR:test-sso-db.postgres.database.azure.com}:${DB_PORT:5432}/${DB_DATABASE:testssodb}?${JDBC_PARAMS:sslmode=require}
    username: ${DB_USER:testsso@test-sso-db}
    password: ${DB_PASSWORD:admMe123}
    driverClassName: org.postgresql.Driver    
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 35
    max-idle: 20
    initial-size: 20
    max-wait: 10000
server:  
  tomcat:
    max-threads: 50
    min-spare-threads: 16
  undertow:
    worker-threads: 32
    direct-buffers: true
    buffers-per-region: 20
    buffer-size: 16000
    io-threads: 4
  port: ${PORT:2205}
  servlet:
    contextPath: ${CONTEXT_PATH:/api/v1/iam}
    swaggerPath: ${SWAGGER_PATH:/api/v1/iam}
keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_AUTH_URL:http://localhost/auth}
  realm: ${KEYCLOAK_REALM:eurowag}
  username: ${KEYCLOAK_USER:wagadmin}
  password: ${KEYCLOAK_PASSWORD:xara2002}
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
generator:
  password:
    lowercase: ${GENERATOR_LOWERCASE:abcdefghijklmnopqrstuvwxyz}
    uppercase: ${GENERATOR_UPPERCASE:ABCDEFGJKLMNPRSTUVWXYZ}
    numbers: ${GENERATOR_NUMBERS:0123456789}
    specials: ${GENERATOR_SPECIALS:"^$?!@%_-:#&"}
    all: ${GENERATOR_ALL:abcdefghijklmnopqrstuvwxyzABCDEFGJKLMNPRSTUVWXYZ0123456789^$?!@%_-:#&}