swagger: '2.0'
info:
  description: EW REST API for SSO - Authentication Service
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  contact:
    email: info@karumien.com
  title: Definitions
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/iam
schemes:
  - http
paths:
  /def/ErrorDataCodeLogin:
    get:
      operationId: getErrorDataCodeLogin
      responses:
        200:
          description: "Specification of enum '#/definitions/ErrorDataCodeLogin'"
          schema:
            $ref: '#/definitions/ErrorDataCodeLoginSpecification'      
  /def/ErrorDataCodeCredentials:
    get:
      operationId: getErrorDataCodeCredentials
      responses:
        200:
          description: "Specification of enum '#/definitions/ErrorDataCodeCredentials'"
          schema:
            $ref: '#/definitions/ErrorDataCodeCredentialsSpecification'
definitions:  
  ErrorCode:
    type: string
    description: Master Error Code
    enum:
      - CLIENT_ERROR
  ErrorDataCodeLoginSpecification:
    type:
      object
    properties:
      enum:
        type: array
        items:
          $ref: "#/definitions/ErrorDataCodeLogin"
  ErrorDataCodeLogin: &ERROR_DATA_CODE_LOGIN
    type: string
    description: Error codes for login flow
    enum: 
      - configure-totp
      - update-password
      - update-profile
      - verify-email
  ErrorDataCodeCredentialsSpecification:
    type:
      object
    properties:
      enum:
        type: array
        items:
          $ref: "#/definitions/ErrorDataCodeCredentials"
  ErrorDataCodeCredentials: &ERROR_DATA_CODE_CREDENTIALS
    type: string
    description: Error codes for create credentials flow
    enum:
      - invalid-username
      - invalid-password  
  ErrorData:
    type: object
    description: EW ErrorMessage model data
    required:
    - code
    properties:
      code:
        type: string
        description: ie. invalid-phone-number-format
        maxLength: 50
      attribute: 
        type: string
        maxLength: 250
        description: ie. phoneNumberPrimary
      description:
        type: string
        maxLength: 1000
        description: ie. Invalid phone number format. Valid is XXX XXX XXX
      data:
        type: object
  ErrorMessage:
    type: object
    description: EW ErrorMessage model
    required:
    - errno
    - errcode
    properties:
      errno: 
        type: integer
        default: -1
      errcode: 
        $ref: "#/definitions/ErrorCode"
      errmsg: 
        type: string
        maxLength: 250
        description: Optional error message
      errdata:
        type: array
        items:
          $ref: "#/definitions/ErrorData"