swagger: '2.0'
info:
  description: REST API for SSO Customer Service
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  contact:
    email: info@karumien.com
  title: Customer Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/sso
schemes:
  - http
paths:
  /customers:
    post:
      summary: Create Customer
      description: Create Customer in target SSO
      operationId: createCustomer
      parameters:
        - in: body
          name: Customer
          description: The Customer to create
          schema:
            $ref: '#/definitions/CustomerBaseInfo'
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/CustomerBaseInfo'
  /customers/{id}:
    get:
      summary: "Get detail of the given Customer"
      description: "Method returns detail information about Customer."
      operationId: "getCustomer"
      parameters:
        - name: id
          in: path
          description: Filtering by Customer Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Customer's info
          schema:
            $ref: '#/definitions/CustomerBaseInfo'
        '404':
          description: Not found
    delete:
      summary: "Remove existing Customer"
      operationId: "deleteCustomer"
      parameters:
        - name: id
          in: path
          description: Filtering by Customer Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully removed existing Customer
        '404':
          description: Customer Not found
definitions:
  CustomerBaseInfo:
    type: object
    description: "Basic information about Customer"
    required:
      - name
      - compRegNo
    properties:
      id:
        type: string
        description: Customer Unique ID 
      name:
        type: string
        description: "Customer name"
        maxLength: 50
      compRegNo:
        type: string
        maxLength: 20
        description: Customer Registration Number
    example:
      id: fd65248c-f3aa-4310-8fcf-91eacdd324xx
      name: Customer s.r.o.
      compRegNo: 6484605
      