swagger: '2.0'
info:
  description: EW REST API for SSO - Role Service
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  contact:
    email: info@karumien.com
  title: Role Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/iam
schemes:
  - http
paths:
  /roles:
    post:
      summary: Create role
      description: Create role in target SSO
      operationId: createRole
      parameters:
        - in: body
          name: role
          description: The role to create
          schema:
            $ref: '#/definitions/RoleInfo'
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/RoleInfo'
  /roles/{roleId}:
    get:
      summary: "Get detail of the given role"
      description: "Method returns detail information about role."
      operationId: "getRole"
      parameters:
        - name: roleId
          in: path
          description: Filtering by role Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned role's info
          schema:
            $ref: '#/definitions/RoleInfo'
        '410':
          description: Gone
    delete:
      summary: "Remove existing role"
      operationId: "deleteRole"
      parameters:
        - name: roleId
          in: path
          description: Filtering by role Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully removed existing role
        '410':
          description: role Gone
definitions:
  RoleInfo:
    type: object
    description: "Basic information about Role"
    required:
      - roleId
    properties:
      roleId:
        type: string
        description: "Unique Role ID (Role Name)"
        maxLength: 50
      description: 
        type: string
        description: "Role description"
        maxLength: 255
      accountNumber:
        type: string
        description: Custom role for account
      translation:
        type: string
        description: "Role translation"
        maxLength: 255
      roles:
        type: array
        items:
          type: string
      rights:
        type: array
        items:
          type: string