swagger: '2.0'
info:
  description: EW REST API for SSO - Identity Service - Management of Identities (Users/Contacts)
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  Identity:
    email: info@karumien.com
  title: Identity Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/iam
schemes:
  - http
paths:
  /identities:
    post:
      summary: Create Identity
      description: Create Identity in target SSO
      operationId: createIdentity
      parameters:
        - in: body
          name: identity
          description: The Identity to create
          schema:
            $ref: '#/definitions/IdentityInfo'
            example:
              lastName: Novak
              firstName: Karel
              username: KajaN
              email: KajaN@eurowag.com
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/IdentityInfo'
            example:
              crmContactId: 6287994b-0245-4ca7-8eb4-777230b2f91f
              lastName: Novak
              firstName: Karel
              username: KajaN
              email: KajaN@eurowag.com
  /identities/{crmContactId}:
    get:
      summary: "Get detail of the given Identity"
      description: "Method returns detail information about Identity."
      operationId: getIdentity
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully returned Identity's info
          schema:
            $ref: '#/definitions/IdentityInfo'
        '404':
          description: not found
    delete:
      summary: "Remove existing Identity"
      operationId: deleteIdentity
      parameters:
        - name: id
          in: path
          description: Filtering by Identity Unique ID
          required: true
          type: string       
      responses:
        '200':
          description: Successfully removed existing Identity
        '404':
          description: Identity not found
  /identities/{crmContactId}/credentials:
    post:
      summary: "Create Identity credentials"
      description: "Method to create Identity credentials for given customer"
      operationId: createIdentityCredentials
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
        - in: body
          name: credentials
          description: The Credentials for Identity to create/change
          schema:
            $ref: '#/definitions/Credentials'
            example:
              username: "midie"
              password: "#123456."
      responses:
        '201':
          description: "Identity creadentials has been created"
          schema:
            $ref: '#/definitions/Policy'      
        '404':
          description: Identity not found
          schema:
            $ref: '#/definitions/Policy'      
        '406':
          description: Can't create Identity's credentials - becase Policy Settings    
          schema:
            $ref: '#/definitions/Policy'
  /identities/{crmContactId}/pin:
    put:
      summary: "Create/Reset Driver PIN"
      description: "Method to create/reset driver's PIN for given driver"
      operationId: "createDriverPin"
      parameters:
        - name: id
          in: path
          description: Filtering by Driver Unique ID
          required: true
          type: string       
        - in: body
          name: pin
          description: PIN for Driver to create/change
          schema:
            $ref: '#/definitions/DriverPin'
            example:
              pin: "1234"
      responses:
        '201':
          description: "Driver PIN has been created/update"
        '404':
          description: Driver not found  
        '406':
          description: Can't create/update Driver's PIN 
        '501':
          description: Not Implemented Now
  /identities/{crmContactId}/impersonate:
    post:
      summary: "Impersonate Identity"
      description: "Method for impersonation of specified Identity"
      operationId: "impersonateIdentity"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: "Identity has been impersonated"
        '404':
          description: Identity not found
  /identities/{crmContactId}/logout:
    post:
      summary: "Logout Identity's session"
      description: "Method for logout session of specified Identity"
      operationId: "logoutIdentity"
      parameters:
        - name: icrmContactId
          in: path
          description: Filtering by Identity unique CRM ID
          required: true
          type: string       
      responses:
        '200':
          description: "Identity has been logged out of all sessions"
        '404':
          description: Identity not found
  /identities/password/policy:
    get:
      summary: "Returns Password Policy for Identities"
      description: "Method for get Identity's password policy"
      operationId: "getPasswordPolicy"
      responses:
        '200':
          description: "Password Policy Settings"
          schema:
            $ref: '#/definitions/Policy' 
  /identities/{crmContactId}/roles/binary:
    get:
      summary: "Get assigned Roles on Identity in Binary Representation"
      operationId: "getIdentityRolesBinary"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
      produces:
        - text/plain
      responses:
        '200':
          description: Identity's assigned Roles in Binary Representation 
        '404':
          description: Identity not found    
  /identities/{crmContactId}/roles:
    get:
      summary: "Get assigned Roles on Identity"
      operationId: "getIdentityRoles"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
      responses:
        '200':
          description: Identity's assigned roles
          schema:
            type: array
            items:
              $ref: '#/definitions/RoleInfo'
        '404':
          description: Identity not found
    put:
      summary: "Assign roles on Identity"
      operationId: "assignIdentityRoles"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - in: body
          name: roles
          description: List of Identity's ID to assign
          schema:
            type: array
            items:
              type: string                    
      responses:
        '202':
          description: Successfully assigned Roles to Identity
        '404':
          description: Identity not found
    delete:
      summary: "Unassign Roles on Identity"
      operationId: "unassignIdentityRoles"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - in: body
          name: roles
          description: List of Identity's ID to unassign
          schema:
            type: array
            items:
              type: string                    
      responses:
        '202':
          description: Successfully unsassigned Roles from Identity
        '404':
          description: Identity not found
  /identities/{crmContactId}/roles/{roleId}:
    get:
      summary: "Get assigned Roles on Identity"
      operationId: "getIdentityRole"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string   
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string   
      responses:
        '200':
          description: Role is assigned to Identity
        '404':
          description: Identity not found
        '406':
          description: Role not assigned
    put:
      summary: "Assign Role to Identity"
      operationId: "assignIdentityRole"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully assigned Role on Identity
        '404':
          description: Identity not found
        '406':
          description: Role for Identity not assigned
    delete:
      summary: "Remove Role on Identity"
      operationId: "unassignIdentityRole"
      parameters:
        - name: crmContactId
          in: path
          description: Filtering by Identity CRM ID
          required: true
          type: string       
        - name: roleId
          in: path
          description: Filtering by Identity ID
          required: true
          type: string    
      responses:
        '202':
          description: Successfully unassigned Role from Identity
        '404':
          description: Identity not found
        '406':
          description: Role not unassigned
definitions:
  IdentityInfo:
    type: object
    description: "Basic information about Identity"
    required:
      - crmContactId
      - username
    properties:
      crmContactId:
        type: string
        description: Identity's Unique ID 
      lastName:
        type: string
        description: "Last name/ surname of the Identity"
        maxLength: 50
      firstName:
        type: string
        description: "First name of the Identity"
        maxLength: 50
      username:
        type: string
        description: "Nick name of person for game"
        maxLength: 50
      email:
        type: string
        description: "Primary email used primary for password reset"
        maxLength: 100
      phone:
        type: string
        description: "Phone used primary for OTP"
        maxLength: 30
      contactEmail:
        type: string
        description: "Contact email - can be company global"
        maxLength: 100
    example:
      crmContactId: fe29248c-f3aa-4310-8fcf-91eacdd324xx
      lastName: Novak
      firstName: Karel
      username: KajaN
      email: KajaN@eurowag.com
  Credentials:
    type: object
    description: "Object for setting of Identity credential"
    properties:
      temporary:
        type: boolean
#        required: false
        description: "Temporary - need reset after first login"
      password:
        type: string
        example: "#123456."
        maxLength: 50
#        required: true
  DriverPin:
    type: object
    description: "Driver's PIN Definition"
    properties:
      pin:
        type: string
        example: "123456"
        maxLength: 10
  Policy:
    type: object
    description: "Configuration object for Password Policy"
    properties:
      value:
        type: string
        description: "Full policy description"
      minSpecialChars:
        type: integer
        description: "Minimum use special chars in password"
        example: "1"       
      minUpperCase: 
        type: integer
        description: "Minimum use upper case chars in password"
        example: "1"
      minLength:
        type: integer
        description: "Minimum password length"
        example: "8"
      notUseUsername:
        type: boolean
        description: "Use username in password"
        example: "true"
      passwordHistory:
        type: integer
        description: "Use same password from history"
        example: "3"
      minLowerCase:
        type: integer
        description: "Minimum use lower case chars in password"
        example: "1"
      minDigits:
        type: integer
        description: "Minimum use digits in password"
        example: "1"
      passwordExpireDays:
        type: integer
        description: "Password expire in days"
        example: "365"
      hashAlgorithm:
        type: string
        description: "Hash algorithm for password encode"
        example: "pbkdf2-sha256"
      hashIterations:
        type: integer
        description: "Hash iterations for password encode"
        example: "27500"
      passwordBlacklist:
        type: boolean
        description: "Use blacklist for passwords"
      regexPattern:
        type: string
        description: "REGEX pattern for password validation"
        example: ".*"
  RoleInfo:
    type: object
    description: "Basic information about Role"
    required:
      - roleId
    properties:
      roleId:
        type: string
        description: "Unique Role ID (Role Name)"
        maxLength: 50
      description:
        type: string
        description: "Role description"
        maxLength: 255
      clientId:
        type: string
        maxLength: 250
        description: Client Id (for client roles)
      clientRole:
        type: boolean
        description: "Identify Client Role (not realm role)"
    example:
      id: fd65248c-f3aa-4310-8fcf-91eacdd324xx
      name: First Role
      description: Role description
      clientId: 9abedf80-7413-4751-9b73-84d07a32e11c
      clientRole: true